language: java
jdk: oraclejdk8
dist: trusty
install: true
script: mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
after_success:
  - mvn clean test coveralls:report
cache:
  directories:
    - $HOME/.m2
notifications:
  email: false
