language: java
jdk: oraclejdk8
dist: trusty
install: true
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - bundle exec rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

after_success:
  - mvn clean test coveralls:report
cache:
  directories:
    - $HOME/.m2
notifications:
  email: false
